name: Deploy to GCP - DEV
on:
  push:
    branches: develop
jobs:
  ci-cd:
    name: CI/CD
    uses: felipemenezesdm/laravel-deploy-actions/.github/workflows/gcp-infra-dev.yml@v1
    secrets: inherit
