name: Deploy to GCP - HOM & PROD
on:
  push:
    branches: main
jobs:
  ci-cd:
    name: CI/CD
    uses: felipemenezesdm/laravel-deploy-actions/.github/workflows/gcp-infra.yml@v1
    secrets: inherit
